name: Another Angle
favicon: null
layout_spectrum: 0.7515644284430891
typography_spectrum: 0.36176832928322256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5654511009342968
  lightness: 0.4763787214178592
  saturation: 0.759512453339994
  rhythmicContrast: 0.5900748311541975
purpose: []
