name: Another Angle
favicon: null
layout_spectrum: 0.8034267872571945
typography_spectrum: 0.023128834320232272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6421643937937915
  lightness: 0.029454190051183105
  saturation: 0.3090891425963491
  rhythmicContrast: 0.8641746127977967
purpose: []
