name: Another Angle
favicon: null
layout_spectrum: 0.7037674046587199
typography_spectrum: 0.049400914926081896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7490495243109763
  lightness: 0.19786742143332958
  saturation: 0.717743378598243
  rhythmicContrast: 0.37154432851821184
purpose: []
