name: Another Angle
favicon: null
layout_spectrum: 0.7350565022788942
typography_spectrum: 0.7344724438153207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.11226329253986478
  lightness: 0.5118788524996489
  saturation: 0.45626159058883786
  rhythmicContrast: 0.2547326795756817
purpose: []
